name: Arduino Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict

  compile-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:mega:cpu=atmega2560
          - esp8266:esp8266:d1_mini
          - esp32:esp32:esp32

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: arduino:avr
              source-url: https://downloads.arduino.cc/packages/package_index.json
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - examples
          libraries: |
            - source-path: ./
          verbose: true 